{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dash-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: dash-prometheus
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: dash-prometheus
{{- end }}
