- name: Installation of CarbonBlack
  shell: /bin/bash "{{ CarbonBlack_installation_script }}"
  args:
    chdir: "{{ os_repo_path }}/CarbonBlack"
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
  tags: carbonblack
- name: Proxy setting for CarbonBlack
  lineinfile:
    dest:  /var/lib/cb/sensorsettings.ini
    line: Proxy={{ proxy_host}}:{{ proxy_port}}
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
  tags: carbonblack
- name: Restart cbdaemon service
  service:
    name: cbdaemon
    state: restarted
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
  tags: carbonblack
