vsphere_hostname: 'eu1vc1.eu1.sp.ibm.local'
vsphere_datacenter: 'EU1-AMS03'
vsphere_cluster: 'EU1-C1'
vsphere_folder: 'Ansible'
vsphere_datastore: 'eu1-c1-vsan'
dns_servers: 
  - 158.87.52.2
  - 158.87.52.3
dns_domain: "sr1.eu1.sp.ibm.local"
virtual_machines: 
        - name: 'eu1sr1lptajgfs1'
          template: 'ubuntu1604_latest'
          vswitch: 'vxw-dvs-70-virtualwire-3-sid-7003-eu1-sres1-app-internal1'
          ip: '158.87.52.211'
          netmask: '255.255.254.0'
          gateway: '158.87.52.1'
          vcpus: '2'
          mem_mb: '4096'
        - name: 'eu1sr1lptajgfs2'
          template: 'ubuntu1604_latest'
          vswitch: 'vxw-dvs-70-virtualwire-3-sid-7003-eu1-sres1-app-internal1'
          ip: '158.87.52.212'
          netmask: '255.255.254.0'
          gateway: '158.87.52.1'
          vcpus: '2'
          mem_mb: '4096'
        - name: 'eu1sr1lptajgfs3'
          template: 'ubuntu1604_latest'
          vswitch: 'vxw-dvs-70-virtualwire-3-sid-7003-eu1-sres1-app-internal1'
          ip: '158.87.52.213'
          netmask: '255.255.254.0'
          gateway: '158.87.52.1'
          vcpus: '2'
          mem_mb: '4096'

virtual_machines_additional_disks:
        - name: 'eu1sr1lptajgfs1'
          disks:
                - size_gb: 200
                  state: present
                  unit_number: 1
                  scsi_type: '{{ scsi_type }}' # defaults from role
                  datastore: '{{ vsphere_datastore }}'
                  scsi_controller: '{{ scsi_controller }}' # defaults from role
                  type: '{{ disk_provisioning_type }}' # defaults from role
        - name: 'eu1sr1lptajgfs2'
          disks:
                - size_gb: 200
                  state: present
                  unit_number: 1
                  scsi_type: '{{ scsi_type }}' # defaults from role
                  datastore: '{{ vsphere_datastore }}' 
                  scsi_controller: '{{ scsi_controller }}' # defaults from role
                  type: '{{ disk_provisioning_type }}' # defaults from role

