{{- if .Values.alertManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dash-alertmanager
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: dash-alertmanager
spec:
  ports:
    - name: http
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: dash-alertmanager
  type: "ClusterIP"
{{- end }}