---
{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: dash-prometheus
  name:  {{ .Release.Name }}-dash-prometheus
{{- end }}

---
{{- if .Values.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: dash-prometheus
  name: {{ .Release.Name }}-dash-prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - ingresses
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
      - ingresses
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
{{- end }}

---
{{- if .Values.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: dash-prometheus
  name: {{ .Release.Name }}-dash-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-dash-prometheus
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-dash-prometheus
{{- end }}
