  - name: Collect Edge VM Folder ID
    uri:
      url: "https://{{ vcenter }}/rest/vcenter/folder?filter.names={{ vcenter_edgevm_folder }}"
      validate_certs: no
      headers:
        Accept: "application/json"
        Content-Type: "application/json"
        Cookie: "{{vc_login.set_cookie}}"
      method: get
      body_format: json
    register: output_edgevm_folder

  - name: Save Edge VM Folder ID to Variable
    set_fact:
      edgevm_folder_id: "{{ output_edgevm_folder.json.value[0].folder }}"
