proxyEnvs:
  - name: HTTP_PROXY
    value: "http://ag1pdr1prx.pdr1.poc.ispw.ibm.local:8080"
  - name: HTTPS_PROXY
    value: "http://ag1pdr1prx.pdr1.poc.ispw.ibm.local:8080"
  - name: NO_PROXY
    value: "localhost,127.0.0.1,100.120.35.17,pocpdr1icp1.pdr1.poc.ispw.ibm.local:8500"
