proxyEnvs:
  - name: HTTP_PROXY
    value: "http://100.72.69.4:8080"
  - name: HTTPS_PROXY
    value: "http://100.72.69.4:8080"
  - name: NO_PROXY
    value: "localhost,127.0.0.1,,172.30.0.1,svc.cluster.local,w3.apihub.ibm.com,w3.api.ibm.com,w3-dev.ibm.com,w3-03.ibm.com,bluepages.ibm.com,mycluster.icp,eu1sr1lpta1ctl1.sr1.eu1.sp.ibm.local,*.sr1.eu1.sp.ibm.local"
