proxyEnvs:
  - name: HTTP_PROXY
    value: "http://100.64.69.4:8080"
  - name: HTTPS_PROXY
    value: "http://100.64.69.4:8080"
  - name: NO_PROXY
    value: "localhost,127.0.0.1,,172.30.0.1,svc.cluster.local,158.87.48.43,10.10.10.1,10.10.10.0,w3.apihub.ibm.com,w3.api.ibm.com,w3-dev.ibm.com,w3-03.ibm.com,bluepages.ibm.com,mycluster.icp,ag1sr1lpta1ctl1.sr1.ag1.sp.ibm.local,*.sr1.ag1.sp.ibm.local"
