sudo: required

env:
  - VPN=openvpn
    DOCKER_IMAGE_SUFFIX=
  - VPN=ipsec	
    DOCKER_IMAGE_SUFFIX=-ipsec

services:
  - docker
script: 
  - bash .build/build.sh
notifications:
  slack: ibm-tia-process-auto:${SLACK_KEY}
