apiVersion: v1
data:
  alertmanager.yml: |-
    global:
    receivers:
      - name: default-receiver
        slack_configs:
        - api_url: 'https://hooks.slack.com/services/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'
          channel: '#sp-monitoring'
          text: "<!channel> \ndescription: {{ .CommonAnnotations.description }}\nsummary: {{ .CommonAnnotations.summary }}"
          send_resolved: true
    route:
      group_by: ['alertname','instance','kubernetes_namespace','pod','container','node']
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 3h
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"alertmanager.yml":"global:\nreceivers:\n  - name: default-receiver\n    slack_configs:\n    - api_url: 'https://hooks.slack.com/services/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'\n      channel: '#sp-monitoring'\n      send_resolved: true\nroute:\n  group_by: ['alertname','instance','kubernetes_namespace','pod','container','node']\n  group_wait: 10s\n  group_interval: 5m\n  receiver: default-receiver\n  repeat_interval: 3h"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"monitoring-prometheus","component":"alertmanager"},"name":"monitoring-prometheus-alertmanager","namespace":"kube-system","selfLink":"/api/v1/namespaces/kube-system/configmaps/monitoring-prometheus-alertmanager"}}
  labels:
    app: monitoring-prometheus
    component: alertmanager
  name: monitoring-prometheus-alertmanager
  namespace: kube-system

