apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"monitoring-exporter","component":"collectdexporter"},"name":"monitoring-exporter","namespace":"kube-system"},"spec":{"template":{"metadata":{"labels":{"app":"monitoring-exporter","component":"collectdexporter"},"name":"monitoring-exporter"},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"management","operator":"In","values":["true"]}]}]}}},"containers":[{"args":["-collectd.listen-address=:25826"],"image":"ibmcom/collectd-exporter:0.3.1","name":"collectd-exporter","ports":[{"containerPort":9103,"name":"metrics"},{"containerPort":25826,"name":"collector","protocol":"UDP"}]}],"tolerations":[{"effect":"NoSchedule","key":"dedicated","operator":"Exists"}]}}}}
  creationTimestamp: 2018-03-21T05:20:08Z
  generation: 1
  labels:
    app: monitoring-exporter
    component: collectdexporter
  name: monitoring-exporter
  namespace: kube-system
  resourceVersion: "50710636"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/monitoring-exporter
  uid: 85a50f42-2cc7-11e8-bc77-005056bbded7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-exporter
      component: collectdexporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monitoring-exporter
        component: collectdexporter
      name: monitoring-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: management
                operator: In
                values:
                - "true"
      containers:
      - args:
        - -collectd.listen-address=:25826
        image: ibmcom/collectd-exporter:0.3.1
        imagePullPolicy: IfNotPresent
        name: collectd-exporter
        ports:
        - containerPort: 9103
          name: metrics
          protocol: TCP
        - containerPort: 25826
          name: collector
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-03-21T05:20:08Z
    lastUpdateTime: 2018-03-21T05:20:08Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
