apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"monitoring-prometheus","component":"kubestatemetrics"},"name":"monitoring-prometheus-kubestatemetrics","namespace":"kube-system"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"monitoring-prometheus","component":"kubestatemetrics"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"management","operator":"In","values":["true"]}]}]}}},"containers":[{"image":"ibmcom/kube-state-metrics:v1.2.0","imagePullPolicy":"IfNotPresent","name":"kubestatemetrics","ports":[{"containerPort":8080}],"resources":{}}],"tolerations":[{"effect":"NoSchedule","key":"dedicated","operator":"Exists"}]}}}}
  creationTimestamp: 2018-03-21T05:20:09Z
  generation: 2
  labels:
    app: monitoring-prometheus
    component: kubestatemetrics
  name: monitoring-prometheus-kubestatemetrics
  namespace: kube-system
  resourceVersion: "50710714"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/monitoring-prometheus-kubestatemetrics
  uid: 85d62dce-2cc7-11e8-bc77-005056bbded7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-prometheus
      component: kubestatemetrics
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monitoring-prometheus
        component: kubestatemetrics
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: management
                operator: In
                values:
                - "true"
      containers:
      - image: ibmcom/kube-state-metrics:v1.2.0
        imagePullPolicy: IfNotPresent
        name: kubestatemetrics
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-03-21T05:20:09Z
    lastUpdateTime: 2018-03-21T05:20:09Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
