version: '2'
services:
  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - /var/lib/docker/data/sasg_data/postgres:/var/lib/postgresql/data
