

- name: copy terraform install file
  copy:
    src: "{{ role_path }}/files/terraform_0.11.11_linux_amd64.zip"
    dest: /home/icpenable
    owner: icpenable
    group: users
    mode: 0644
  become: yes

#  wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip

- name: unzip Terraform file
  shell: unzip terraform_0.11.11_linux_amd64.zip
  become: yes

- name: move it a directory searched for executables
  shell: mv terraform /usr/local/bin/
  become: yes

#- name: Install it
#  shell: install terraform /usr/local/bin/
#  become: yes
