{{- if .Values.alertmanager_builtin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kube-alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.alertmanager_builtin.svc_name }}.{{ .Values.alertmanager_builtin.namespace }}.svc.cluster.local
  {{- end}}