apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dash-token
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
   dash-token-key: {{ .Values.dash_proxy.dashToken | b64enc | quote }}