{{- if .Values.prometheus.enabled }}
{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: {{ .Release.Name }}-node-exporter-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
