# Folder to provision the new VMs in, does not need to exist in vSphere
# This is the folder in vCenter into which the VM will appear
folder: ""

####  The available VM Template from which this solution will be based.
vmtemplate: "icp_30012019"
#vmtemplate: "ubuntu1604_latest"


ansible_ssh_user: 'icpenable'

### Network Information . The Segment information..
# The domain name that represents the NSX Segment
domain: "sres01.poc.ispw.ibm.local"
# The NSX Network identifier into which the VM will be provisioned.
network_label: "vxw-dvs-78-virtualwire-5-sid-5005-ag1-sres1-app-internal1"
#network_label: "vxw-dvs-31-virtualwire-190-sid-5025-dr500-app-internal01"
#  {{ prefix }}{{ suffix }}
# This represents the IP address for the VM on that NSX Segment.
# This needs to be a valid IP address and must come from the Platform regional
# iPAM spreadsheet.
# Finally.. NOTE that this ip addres is actually set in the inventory file
# See the "vms-to-deploy" file
#custom_ip:

### Other .. these are items that are being tested
notes1: " this is a"
notes2: "note"
guest_id: ubuntu64Guest
vmprefix: "gz"
