vsphere_hostname: 'ag1vc1.ag1.sp.ibm.local'
vsphere_datacenter: 'AG1-WDC04'
vsphere_cluster: 'AG1-C1'
vsphere_folder: 'Ansible'
vsphere_datastore: 'ag1-c1-vsan'
dns_servers: 
  - 158.87.48.2
  - 158.87.48.3
dns_domain: "sr1.ag1.sp.ibm.local"
virtual_machines: 
        - name: 'ag1sr1lpta1gfs1'
          template: 'ubuntu1604_latest'
          vswitch: 'vxw-dvs-78-virtualwire-5-sid-5005-ag1-sres1-app-internal1'
          ip: '158.87.48.76'
          netmask: '255.255.254.0'
          gateway: '158.87.48.1'
          vcpus: '2'
          mem_mb: '4096'
        - name: 'ag1sr1lpta1gfs2'
          template: 'ubuntu1604_latest'
          vswitch: 'vxw-dvs-78-virtualwire-5-sid-5005-ag1-sres1-app-internal1'
          ip: '158.87.48.77'
          netmask: '255.255.254.0'
          gateway: '158.87.48.1'
          vcpus: '2'
          mem_mb: '4096'
        - name: 'ag1sr1lpta1gfs3'
          template: 'ubuntu1604_latest'
          vswitch: 'vxw-dvs-78-virtualwire-5-sid-5005-ag1-sres1-app-internal1'
          ip: '158.87.48.78'
          netmask: '255.255.254.0'
          gateway: '158.87.48.1'
          vcpus: '2'
          mem_mb: '4096'

virtual_machines_additional_disks:
        - name: 'ag1sr1lpta1gfs1'
          disks:
                - size_gb: 200
                  state: present
                  unit_number: 1
                  scsi_type: '{{ scsi_type }}' # defaults from role
                  datastore: '{{ vsphere_datastore }}'
                  scsi_controller: '{{ scsi_controller }}' # defaults from role
                  type: '{{ disk_provisioning_type }}' # defaults from role
        - name: 'ag1sr1lpta1gfs2'
          disks:
                - size_gb: 200
                  state: present
                  unit_number: 1
                  scsi_type: '{{ scsi_type }}' # defaults from role
                  datastore: '{{ vsphere_datastore }}' 
                  scsi_controller: '{{ scsi_controller }}' # defaults from role
                  type: '{{ disk_provisioning_type }}' # defaults from role
        

