  - name: GET VXLAN (virtualwire) details
    uri:
      url: "https://{{ nsx_manager }}/api/2.0/vdn/virtualwires?name={{ provider_transit }}"
      force_basic_auth: yes
      method: GET
      user: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      status_code:
        - 200
      validate_certs: no
      headers:
        Accept: "application/json"
        Content-Type: "application/json"
        Cookie: "{{vc_login.set_cookie}}"
      return_content: yes
    register: output_provider_transit_wire

  - set_fact:
      provider_transit_id: "{{ output_provider_transit_wire.json[0].objectId }}"
