---
# This is the file the drives the orchestration of the steps ( i.e. roles and tasks)
# the 'hosts' variable references the elements of the inventory that will
# be provisions
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
#PROD vars files
    - ../../region-configs/{{ region_type }}/{{ region }}/region-answerfile.yml
    - ../../network-config/{{ region_type }}/{{ region }}/{{ dres_name }}-network-answerfile.yml
    - DRES-std-answerfile.yml

  vars_prompt:
      - name: "vcenter_user"
        prompt: "vCenter User"
        private: no
      - name: "vcenter_pwd"
        prompt: "vCenter Password"
        private: yes
      - name: "region"
        prompt: "Region: (eu1, ag1, ap1)"
        private: no
      - name: "region_type"
        prompt: "Region Type: (prod, non-prod)"
        private: no
      - name: "dres_name"
        prompt: "DRES Name"
        private: no

##########################################
# The following represent the roles that will be executed during this playbook.
# Each of these roles is associated to a subdirectory under the roles directory
# These are executed in the order they are listed.
##########################################

  roles:
##########################################
#Gather details about the infrastructure
##########################################
     - generate-vcenter-login-token
     - gather-moid-for-edge-cluster
     - gather-moid-for-datacenter
     - gather-moid-for-edge-datastore
     - gather-moid-for-dlrVMfolder
     - gather-moid-for-edgeVMfolder
     - gather-network-edges-all
     - gather-network-edges-agg-esg-id
     - gather-network-edges-pdr-esg-id
     - gather-network-edges-sl-svc-esg-id
     - gather-network-edges-sres-esg-id
     - gather-network-edges-DLR-id
     - gather-network-edges-RES-ESG-id
     - gather-network-edges-VPN-ESG-id
     # - gather-debug
###########################
#Apply changes below here:
# Below roles apply individual fixups to an Edge by enabling (uncommenting) as needed below:
#############################################################################################
     - configure-edge-dns-forwarders
     - configure-edge-dns-client
     - configure-edge-syslog
     - change-edge-logging
     - change-edge-appliance-RES-ESG
     - change-edge-appliance-VPN-ESG
     - change-edge-appliance-DLR
     - change-edge-resource-reservation
#############################################################################
# Below roles pertains to tasks needed outside of the DRES.
#############################################################################
     # - configure-dres-fw-section
     # - transit-edge-dres-route
