version: '2'
networks:
  host-only:
    external:
      name: host-only 
  default:
    external:
      name: ipvlan
services:
  sasgc:
    image: gts-tia-sasg-dev-docker-local.artifactory.swg-devops.com/sasg_build:${SASGC_VERSION}
    read_only: true
    tmpfs:
      - /etc/nginx/conf.d:exec
      - /sasg:exec
      - /var:exec
      - /tmp:exec
      - /tmp/log:exec
      - /run:exec
    cap_add:
      - NET_ADMIN
    networks:
      host-only:
      default:
        ipv4_address: ${IP}
    volumes:
      - ${CLIENTDIR}/${SASFW}/vars:/opt/sasg/sasg_install/vars
      - ${CLIENTDIR}/${SASFW}/keys:/opt/sasg/sasg_install/keys
      - ${CLIENTDIR}/${SASFW}/logs:/sasg/logs
      - ${CLIENTDIR}/${SASFW}/Nginx:/sasg/Nginx
      - iptables:/etc/iptables
      - ipset:/etc/ipset.d
      - sasg-configs:/sasg/configs
      - /etc/resolv.conf:/etc/resolv.conf
    environment:
      - IPVLAN_GW=${IPVLAN_GW}
      - HOST_ONLY_GW=${HOST_ONLY_GW}
      - HOST_IP=${HOST_IP}
  checker:
    image: gts-tia-sasg-dev-docker-local.artifactory.swg-devops.com/sasg-sidecar-checker:${CHECKER_VERSION}
    read_only: true
    tmpfs:
      - /tmp
      - /var/spool/cron
    volumes:
      - ${CERT}:/certs/client.cert:ro
      - ${KEY}:/certs/client.key:ro
      - /var/log:/host/logs
      - ./logs/Firewall:/host/logs/fw
      - ./logs/VPN:/host/logs/vpn
      - ./gcm:/sasg/gcm
      - /etc/ssh/sshd_config:/host/configs/sshd_config:ro
      - /etc/pam.d/system-auth:/host/configs/system-auth:ro
      - iptables:/sasg/iptables:ro
      - ipset:/sasg/ipset:ro
      - sasg-configs:/sasg/configs:ro
      - ./upload-hashes:/root/upload-hashes
      - ./update-info:/host/update-info
    network_mode: "service:sasgc"
    environment:
      - DOCKER_HOST_NAME=${DOCKER_HOST_NAME}
      - LOGPUSH_IP=${LOGPUSH_IP}
      - LOGPUSH_PORT=${LOGPUSH_PORT}
      - CRON_UPLOAD_LOGS=${CRON_UPLOAD_LOGS}
      - CRON_CHECK_CONFIG=${CRON_CHECK_CONFIG}
      - HOST_IP=${HOST_IP}

volumes:
  iptables:
  ipset:
  sasg-configs:
