apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-anyuid-clusterrole-copy
rules:
- apiGroups:
  - extensions
  resourceNames:
  - ibm-anyuid-psp-copy
  resources:
  - podsecuritypolicies
  verbs:
  - use
