proxyEnvs:
  - name: HTTP_PROXY
    value: "http://100.72.69.4:8080"
  - name: HTTPS_PROXY
    value: "http://100.72.69.4:8080"
  - name: NO_PROXY
    value: "localhost,127.0.0.1,158.87.52.120,100.127.128.1,10.10.10.0,w3.apihub.ibm.com,w3.api.ibm.com,w3-dev.ibm.com,w3-03.ibm.com,bluepages.ibm.com,mycluster.icp,eu1sr1icp2.sr1.eu1.sp.ibm.local:8500"
