  - name: POST DLR Edge Logging Level
    uri:
      url: "https://{{ nsx_manager }}/api/4.0/edges/{{ dlr_id }}/logging?level={{edge_log_level}}&async=true"
      force_basic_auth: yes
      method: POST
      user: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      status_code:
        - 202
      validate_certs: no
      headers:
        Accept: "application/json"
        Content-Type: "application/json"
        Cookie: "{{vc_login.set_cookie}}"
    register: dlr_log_config

  - name: POST RES-ESG Edge Logging Level
    uri:
      url: "https://{{ nsx_manager }}/api/4.0/edges/{{ res_esg_id }}/logging?level={{edge_log_level}}&async=true"
      force_basic_auth: yes
      method: POST
      user: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      status_code:
        - 202
      validate_certs: no
      headers:
        Accept: "application/json"
        Content-Type: "application/json"
        Cookie: "{{vc_login.set_cookie}}"
    register: res_esg_log_config

  - name: POST VPN-ESG Edge Logging Level
    uri:
      url: "https://{{ nsx_manager }}/api/4.0/edges/{{ vpn_esg_id }}/logging?level={{edge_log_level}}&async=true"
      force_basic_auth: yes
      method: POST
      user: "{{ vcenter_user }}"
      password: "{{ vcenter_pwd }}"
      status_code:
        - 202
      validate_certs: no
      headers:
        Accept: "application/json"
        Content-Type: "application/json"
        Cookie: "{{vc_login.set_cookie}}"
    register: vpn_esg_log_config
