apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "proxy-test-chart.fullname" . }}
  labels:
    app: {{ template "proxy-test-chart.name" . }}
    chart: {{ template "proxy-test-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "proxy-test-chart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "proxy-test-chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.proxyEnvs | indent 10 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
