---
- name: gather moid for private uplink portgroup
  vcenter_gather_moids:
    hostname: "{{ vcenter }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pwd }}"
    datacenter_name: "{{ vcenter_dc }}"
    portgroup_name: "{{ priv_ns_portgroup }}"
    validate_certs: False
  register: gather_moids_priv_pg
  tags: moids
