#!/bin/bash
# simple SASG VIP ping check - reads from list of sasg virtual ips - 
# expects one ip per line.  IP list generated by sasgaas tools server 
# installer - sasg vip1 added to the file - if multi-sasg environment, will
# see more than one vip.
SASGVIPS="/sasg/bin/sasg_vips"

PINGFAIL=""
PINGOK=""
for VIP in `cat $SASGVIPS|egrep -v "^$|^#"`
do

  RET=$(ping -c1 $VIP |grep -E -o "[0-9]{1,3}% packet loss")
  echo "$RET" |grep -qw "0%"
  if [ "$?" -ne 0 ];then
    if [ -z "$PINGFAIL" ];then
       PINGFAIL="${VIP}: ${RET}"
    else
       PINGFAIL="${PINGFAIL}, ${VIP}: ${RET}"
    fi
  else
    if [ -z "$PINGOK" ];then
       PINGOK="${VIP}: ${RET}"
    else
       PINGOK="${PINGOK}, ${VIP}: ${RET}"
    fi
    
  fi
done

if [ ! -z "$PINGFAIL" ];then
  if [ ! -z "$PINGOK" ];then
    # echo out the ips that succeeded too
    echo -e "$PINGFAIL, $PINGOK"
  else
    echo -e "$PINGFAIL"
  fi
  exit 1
else
  echo "$PINGOK"
  exit 0
fi
