---

- vmware_guest:
        hostname: '{{ vsphere_hostname }}'
        username: '{{ vsphere_username }}'
        password: '{{ vsphere_password }}'
        validate_certs: false
        datacenter: '{{ vsphere_datacenter }}'
        folder: '{{ vsphere_folder }}'
        name: '{{ item.name }}'
        template: '{{ item.template }}'
        datastore: '{{ vsphere_datastore }}'
        cluster: '{{ vsphere_cluster }}'
        state: '{{ virtual_machine_state }}'
        hardware:
                memory_mb: '{{ item.mem_mb }}'
                num_cpus: '{{ item.vcpus }}'
        networks:
                - name: '{{ item.vswitch }}'
                  ip: '{{ item.ip }}'
                  netmask: '{{ item.netmask }}'
                  gateway: '{{ item.gateway }}'
                  type: '{{ virtual_machine_networkmethod }}'
        customization:
          dns_servers: '{{ dns_servers }}'
          domain: '{{ dns_domain }}'
        wait_for_ip_address: '{{ waitforip }}'
  delegate_to: localhost
  loop: '{{ virtual_machines }}' 
...
