proxyEnvs:
  - name: HTTP_PROXY
    value: "http://100.64.69.4:8080"
  - name: HTTPS_PROXY
    value: "http://100.64.69.4:8080"
  - name: NO_PROXY
    value: "localhost,127.0.0.1,100.64.84.11,w3.apihub.ibm.com,w3.api.ibm.com,w3-dev.ibm.com,w3-03.ibm.com,bluepages.ibm.com,mycluster.icp,ag1dr47icp1.dr47.ag1.sp.local:8500"
