proxyEnvs:
  - name: HTTP_PROXY
    value: "http://100.64.69.4:8080"
  - name: HTTPS_PROXY
    value: "http://100.64.69.4:8080"
  - name: NO_PROXY
    value: "localhost,127.0.0.1,158.87.50.71,w3.apihub.ibm.com,w3.api.ibm.com,w3-dev.ibm.com,w3-03.ibm.com,bluepages.ibm.com,mycluster.icp,ag1gr1icp3.gr1.ag1.sp.ibm.local:8500"
