---
- name: Restart and enable dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: Start and enable NetworkManager
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

- name: Start and enable the Firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
